import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

/**
 * daily-verses Edge Function
 *
 * "The Moed Coordinate System": maps today's Gregorian date (month:day) to a
 * Chapter:Verse coordinate (e.g. Aug 13 -> 8:13), then selects THREE
 * distinct, real books of the Bible that validly have that chapter:verse,
 * and generates devotional content (Greek/Hebrew word insight + a
 * Tabernacle/Feast/agricultural-season "calendar connection") for each.
 *
 * Content is cached per (month, day) in `moed_daily_content` — generated
 * once, reused forever after (the coordinate for a given calendar date is
 * the same every year). Only this function (service role) ever reads or
 * writes moed_daily_content / month_numerology; both tables have RLS
 * enabled with zero policies on purpose (deny-all to anon/authenticated).
 *
 * Theological guardrail: Gemini is NEVER asked to name a book, chapter, or
 * verse — it only receives already-selected, already-verified references
 * and produces prose commentary. Book identity always comes from the fixed
 * 66-book CANON_BOOKS map below (the Protestant canon), and verse text is
 * always fetched live from scripture.api.bible, never generated by the AI.
 */

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const BIBLE_BASE = 'https://api.scripture.api.bible/v1'
const GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'

// Bible IDs used to cross-validate a candidate reference before it's ever
// shown to a user. AMP is omitted: bible.ts's getBibleId() already falls
// back to KJV for AMP (not resolvable on this API account) — pre-existing,
// out of scope here.
const VALIDATION_BIBLE_IDS = {
  KJV:  'de4e12af7f28f599-02',
  NLT:  '65eec8e0b60e656b-01',
  ESV:  '9879dbb7cfe39e4d-01',
  NKJV: '63097d2a0a2f7db3-01',
} as const

type Testament = 'OT' | 'NT'

const CANON_BOOKS: Record<string, { name: string; testament: Testament; category: string }> = {
  // OT — Law
  GEN: { name: 'Genesis', testament: 'OT', category: 'Law' },
  EXO: { name: 'Exodus', testament: 'OT', category: 'Law' },
  LEV: { name: 'Leviticus', testament: 'OT', category: 'Law' },
  NUM: { name: 'Numbers', testament: 'OT', category: 'Law' },
  DEU: { name: 'Deuteronomy', testament: 'OT', category: 'Law' },
  // OT — History
  JOS: { name: 'Joshua', testament: 'OT', category: 'History' },
  JDG: { name: 'Judges', testament: 'OT', category: 'History' },
  RUT: { name: 'Ruth', testament: 'OT', category: 'History' },
  '1SA': { name: '1 Samuel', testament: 'OT', category: 'History' },
  '2SA': { name: '2 Samuel', testament: 'OT', category: 'History' },
  '1KI': { name: '1 Kings', testament: 'OT', category: 'History' },
  '2KI': { name: '2 Kings', testament: 'OT', category: 'History' },
  '1CH': { name: '1 Chronicles', testament: 'OT', category: 'History' },
  '2CH': { name: '2 Chronicles', testament: 'OT', category: 'History' },
  EZR: { name: 'Ezra', testament: 'OT', category: 'History' },
  NEH: { name: 'Nehemiah', testament: 'OT', category: 'History' },
  EST: { name: 'Esther', testament: 'OT', category: 'History' },
  // OT — Wisdom
  JOB: { name: 'Job', testament: 'OT', category: 'Wisdom' },
  PSA: { name: 'Psalms', testament: 'OT', category: 'Wisdom' },
  PRO: { name: 'Proverbs', testament: 'OT', category: 'Wisdom' },
  ECC: { name: 'Ecclesiastes', testament: 'OT', category: 'Wisdom' },
  SNG: { name: 'Song of Solomon', testament: 'OT', category: 'Wisdom' },
  // OT — Major Prophets
  ISA: { name: 'Isaiah', testament: 'OT', category: 'Major Prophets' },
  JER: { name: 'Jeremiah', testament: 'OT', category: 'Major Prophets' },
  LAM: { name: 'Lamentations', testament: 'OT', category: 'Major Prophets' },
  EZK: { name: 'Ezekiel', testament: 'OT', category: 'Major Prophets' },
  DAN: { name: 'Daniel', testament: 'OT', category: 'Major Prophets' },
  // OT — Minor Prophets
  HOS: { name: 'Hosea', testament: 'OT', category: 'Minor Prophets' },
  JOL: { name: 'Joel', testament: 'OT', category: 'Minor Prophets' },
  AMO: { name: 'Amos', testament: 'OT', category: 'Minor Prophets' },
  OBA: { name: 'Obadiah', testament: 'OT', category: 'Minor Prophets' },
  JON: { name: 'Jonah', testament: 'OT', category: 'Minor Prophets' },
  MIC: { name: 'Micah', testament: 'OT', category: 'Minor Prophets' },
  NAM: { name: 'Nahum', testament: 'OT', category: 'Minor Prophets' },
  HAB: { name: 'Habakkuk', testament: 'OT', category: 'Minor Prophets' },
  ZEP: { name: 'Zephaniah', testament: 'OT', category: 'Minor Prophets' },
  HAG: { name: 'Haggai', testament: 'OT', category: 'Minor Prophets' },
  ZEC: { name: 'Zechariah', testament: 'OT', category: 'Minor Prophets' },
  MAL: { name: 'Malachi', testament: 'OT', category: 'Minor Prophets' },
  // NT — Gospels
  MAT: { name: 'Matthew', testament: 'NT', category: 'Gospels' },
  MRK: { name: 'Mark', testament: 'NT', category: 'Gospels' },
  LUK: { name: 'Luke', testament: 'NT', category: 'Gospels' },
  JHN: { name: 'John', testament: 'NT', category: 'Gospels' },
  // NT — Acts
  ACT: { name: 'Acts', testament: 'NT', category: 'Acts' },
  // NT — Pauline Epistles
  ROM: { name: 'Romans', testament: 'NT', category: 'Pauline Epistles' },
  '1CO': { name: '1 Corinthians', testament: 'NT', category: 'Pauline Epistles' },
  '2CO': { name: '2 Corinthians', testament: 'NT', category: 'Pauline Epistles' },
  GAL: { name: 'Galatians', testament: 'NT', category: 'Pauline Epistles' },
  EPH: { name: 'Ephesians', testament: 'NT', category: 'Pauline Epistles' },
  PHP: { name: 'Philippians', testament: 'NT', category: 'Pauline Epistles' },
  COL: { name: 'Colossians', testament: 'NT', category: 'Pauline Epistles' },
  '1TH': { name: '1 Thessalonians', testament: 'NT', category: 'Pauline Epistles' },
  '2TH': { name: '2 Thessalonians', testament: 'NT', category: 'Pauline Epistles' },
  '1TI': { name: '1 Timothy', testament: 'NT', category: 'Pauline Epistles' },
  '2TI': { name: '2 Timothy', testament: 'NT', category: 'Pauline Epistles' },
  TIT: { name: 'Titus', testament: 'NT', category: 'Pauline Epistles' },
  PHM: { name: 'Philemon', testament: 'NT', category: 'Pauline Epistles' },
  // NT — General Epistles
  HEB: { name: 'Hebrews', testament: 'NT', category: 'General Epistles' },
  JAS: { name: 'James', testament: 'NT', category: 'General Epistles' },
  '1PE': { name: '1 Peter', testament: 'NT', category: 'General Epistles' },
  '2PE': { name: '2 Peter', testament: 'NT', category: 'General Epistles' },
  '1JN': { name: '1 John', testament: 'NT', category: 'General Epistles' },
  '2JN': { name: '2 John', testament: 'NT', category: 'General Epistles' },
  '3JN': { name: '3 John', testament: 'NT', category: 'General Epistles' },
  JUD: { name: 'Jude', testament: 'NT', category: 'General Epistles' },
  // NT — Apocalyptic
  REV: { name: 'Revelation', testament: 'NT', category: 'Apocalyptic' },
}

// ─── Deterministic per-coordinate shuffle (idempotent under concurrent cold starts) ───

function hashSeed(s: string): number {
  let h = 1779033703 ^ s.length
  for (let i = 0; i < s.length; i++) {
    h = Math.imul(h ^ s.charCodeAt(i), 3432918353)
    h = (h << 13) | (h >>> 19)
  }
  return h >>> 0
}

function mulberry32(seed: number) {
  let s = seed
  return function () {
    s |= 0
    s = (s + 0x6d2b79f5) | 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function shuffle<T>(arr: T[], rng: () => number): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

// Round-robins across categories so the candidate order tries diverse
// categories (Law, Wisdom, Gospels, Epistles, ...) before ever repeating one.
function diversityOrder(shuffled: string[]): string[] {
  const byCategory = new Map<string, string[]>()
  for (const code of shuffled) {
    const cat = CANON_BOOKS[code].category
    if (!byCategory.has(cat)) byCategory.set(cat, [])
    byCategory.get(cat)!.push(code)
  }
  const categories = [...byCategory.keys()]
  const result: string[] = []
  let i = 0
  while (result.length < shuffled.length) {
    for (const cat of categories) {
      const arr = byCategory.get(cat)!
      if (arr[i]) result.push(arr[i])
    }
    i++
  }
  return result
}

// ─── Live validation against the real Bible API (never trust a static count) ───

async function fetchVerseText(bibleId: string, book: string, chapter: number, verse: number, apiKey: string): Promise<string | null> {
  const verseId = `${book}.${chapter}.${verse}`
  const res = await fetch(
    `${BIBLE_BASE}/bibles/${bibleId}/verses/${verseId}?content-type=text&include-notes=false&include-titles=false`,
    { headers: { 'api-key': apiKey } }
  )
  if (!res.ok) return null
  const data = await res.json()
  const clean = (data.data?.content ?? '')
    .replace(/<[^>]+>/g, '')
    .replace(/^\s*\[\d+\]\s*/, '')
    .trim()
  return clean
}

interface SelectedRef {
  book: string
  chapter: number
  verse: number
  kjvText: string
}

const OTHER_VERSIONS = ['NLT', 'ESV', 'NKJV'] as const

/**
 * Picks 3 distinct, category-diverse books that genuinely have chapter:verse
 * = month:day, cross-checked against KJV/NLT/ESV/NKJV so a translation-
 * specific gap (e.g. a disputed verse rendered blank in one version) never
 * slips through.
 */
async function selectVerses(month: number, day: number, apiKey: string): Promise<SelectedRef[]> {
  const rng = mulberry32(hashSeed(`${month}:${day}`))
  const ordered = diversityOrder(shuffle(Object.keys(CANON_BOOKS), rng))

  const selected: SelectedRef[] = []
  for (const book of ordered) {
    if (selected.length === 3) break
    if (selected.some((s) => s.book === book)) continue

    const kjvText = await fetchVerseText(VALIDATION_BIBLE_IDS.KJV, book, month, day, apiKey)
    if (!kjvText || kjvText.length < 10) continue

    let allOk = true
    for (const version of OTHER_VERSIONS) {
      const text = await fetchVerseText(VALIDATION_BIBLE_IDS[version], book, month, day, apiKey)
      if (!text || text.length < 10) {
        allOk = false
        break
      }
    }
    if (!allOk) continue

    selected.push({ book, chapter: month, verse: day, kjvText })
  }
  return selected
}

// ─── Gemini: prose only, never asked to name a reference ───

function buildPrompt(selected: SelectedRef[]): string {
  const lines = selected
    .map((s, i) => `Verse ${i + 1}: ${CANON_BOOKS[s.book].name} ${s.chapter}:${s.verse} — "${s.kjvText}"`)
    .join('\n')

  return `You are a biblical scholar and theologian creating devotional content for "The Moed Meditation," a daily scripture app.

STRICT THEOLOGICAL CONSTRAINTS (non-negotiable):
- Ground every explanation strictly and exclusively in the 66 canonical books of the Protestant Bible.
- Do not reference, draw from, or lend credibility to the Apocrypha, extra-biblical texts, New Age concepts, or any secular spiritual framework.
- All Hebrew/Greek word studies must reflect the actual original-language term present in the verse text provided — do not invent a word that isn't in the verse.
- The verse references below have already been selected and verified. Do not alter, question, add to, or comment on them.

For EACH of the 3 verses below, in the same order, produce:
1. "hebrew_greek_word": the single most theologically significant Hebrew or Greek word in this verse, in its original script, with common English rendering.
2. "transliteration": phonetic transliteration.
3. "meaning": 2-3 sentences, rooted in standard lexical scholarship (Strong's, BDB, Thayer's) — no invented etymology.
4. "calendar_connection": 2-4 sentences tying this verse/word to the Tabernacle, the appointed Feasts (Moedim) of Leviticus 23, or the agricultural/harvest season of the ancient Hebrew calendar — whichever is most textually honest. If no strong, genuine connection exists, return an empty string ("") for this field — do not force one, and do not explain why none exists.
5. "prayer_prompt": one sentence, a prayer invitation growing from the above.

${lines}

Respond with ONLY this JSON (no markdown fences, no commentary):
{
  "verses": [
    { "hebrew_greek_word": "...", "transliteration": "...", "meaning": "...", "calendar_connection": "...", "prayer_prompt": "..." },
    { "hebrew_greek_word": "...", "transliteration": "...", "meaning": "...", "calendar_connection": "...", "prayer_prompt": "..." },
    { "hebrew_greek_word": "...", "transliteration": "...", "meaning": "...", "calendar_connection": "...", "prayer_prompt": "..." }
  ]
}`
}

interface GeneratedVerseContent {
  hebrew_greek_word: string
  transliteration: string
  meaning: string
  calendar_connection: string
  prayer_prompt: string
}

function isValidShape(parsed: unknown): parsed is { verses: GeneratedVerseContent[] } {
  if (!parsed || typeof parsed !== 'object') return false
  const verses = (parsed as { verses?: unknown }).verses
  if (!Array.isArray(verses) || verses.length !== 3) return false
  return verses.every(
    (v: unknown) =>
      typeof v === 'object' &&
      v !== null &&
      typeof (v as GeneratedVerseContent).hebrew_greek_word === 'string' &&
      (v as GeneratedVerseContent).hebrew_greek_word.length > 0 &&
      typeof (v as GeneratedVerseContent).transliteration === 'string' &&
      (v as GeneratedVerseContent).transliteration.length > 0 &&
      typeof (v as GeneratedVerseContent).meaning === 'string' &&
      (v as GeneratedVerseContent).meaning.length >= 20 &&
      typeof (v as GeneratedVerseContent).calendar_connection === 'string' &&
      // Empty string is valid — it means Gemini honestly found no genuine
      // connection, rather than forcing one. Only non-empty values must
      // meet the length bar (guards against a truncated/junk response).
      ((v as GeneratedVerseContent).calendar_connection === '' ||
        (v as GeneratedVerseContent).calendar_connection.length >= 20) &&
      typeof (v as GeneratedVerseContent).prayer_prompt === 'string' &&
      (v as GeneratedVerseContent).prayer_prompt.length > 0
  )
}

async function generateDevotionalContent(selected: SelectedRef[], apiKey: string): Promise<{ verses: GeneratedVerseContent[] } | null> {
  const prompt = buildPrompt(selected)

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(`${GEMINI_URL}?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 2048,
            // gemini-2.5-flash "thinking" tokens otherwise eat most of the
            // output budget before any answer text is written, truncating
            // the JSON (finishReason: MAX_TOKENS). Not needed for this task.
            thinkingConfig: { thinkingBudget: 0 },
          },
        }),
      })
      if (!res.ok) continue

      const data = await res.json()
      const raw = data.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
      const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
      const parsed = JSON.parse(cleaned)
      if (isValidShape(parsed)) return parsed
    } catch {
      // retry
    }
  }
  return null
}

// ─── Request handling ───

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

function parseInput(raw: Record<string, unknown>): { month: number; day: number } | { error: string } {
  const now = new Date()
  const month = raw.month !== undefined && raw.month !== null && raw.month !== '' ? Number(raw.month) : now.getUTCMonth() + 1
  const day = raw.day !== undefined && raw.day !== null && raw.day !== '' ? Number(raw.day) : now.getUTCDate()
  if (!Number.isInteger(month) || month < 1 || month > 12) return { error: 'invalid_month' }
  if (!Number.isInteger(day) || day < 1 || day > 31) return { error: 'invalid_day' }
  return { month, day }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY') ?? ''
  const BIBLE_API_KEY = Deno.env.get('BIBLE_API_KEY') ?? ''
  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  )

  try {
    const raw: Record<string, unknown> =
      req.method === 'POST' ? await req.json().catch(() => ({})) : Object.fromEntries(new URL(req.url).searchParams)

    const parsed = parseInput(raw)
    if ('error' in parsed) return jsonResponse({ error: parsed.error }, 400)
    const { month, day } = parsed

    const numerologyRes = await supabase.from('month_numerology').select('theme, explanation').eq('month', month).single()
    const month_numerology = numerologyRes.data ?? null

    const cached = await supabase.from('moed_daily_content').select('verses').eq('month', month).eq('day', day).maybeSingle()
    if (cached.data) {
      return jsonResponse({ month, day, month_numerology, verses: cached.data.verses, source: 'cache' })
    }

    const selected = await selectVerses(month, day, BIBLE_API_KEY)
    if (selected.length < 3) {
      return jsonResponse({ error: 'no_eligible_books', month, day }, 500)
    }

    const content = await generateDevotionalContent(selected, GEMINI_API_KEY)
    if (!content) {
      return jsonResponse({ error: 'generation_failed', month, day }, 502)
    }

    const verses = selected.map((s, i) => ({
      slot: i + 1,
      book_code: s.book,
      book_name: CANON_BOOKS[s.book].name,
      chapter: s.chapter,
      verse: s.verse,
      testament: CANON_BOOKS[s.book].testament,
      original_language: CANON_BOOKS[s.book].testament === 'OT' ? 'Hebrew' : 'Greek',
      hebrew_greek_word: content.verses[i].hebrew_greek_word,
      transliteration: content.verses[i].transliteration,
      meaning: content.verses[i].meaning,
      calendar_connection: content.verses[i].calendar_connection,
      prayer_prompt: content.verses[i].prayer_prompt,
    }))

    const { error: insertErr } = await supabase.from('moed_daily_content').insert({ month, day, verses })
    // 23505 = unique_violation: lost a cold-start race to a concurrent
    // request for the same coordinate. Fine — this caller still returns its
    // own freshly generated content below.
    if (insertErr && insertErr.code !== '23505') {
      console.error('moed_daily_content insert failed', insertErr)
    }

    return jsonResponse({ month, day, month_numerology, verses, source: 'generated' })
  } catch (err) {
    return jsonResponse({ error: 'internal_error', detail: String(err) }, 500)
  }
})
